### ISSUE TITLE
ImportError:cannot import name 'ops' from e2edet

### ISSUE THREAD

**Issue by Zhuyuan-yuan** [kienduynguyen/BoxeR#1]
when I run box_attn_test.py  ,this promble is found. 
<img width="498" alt="image" src="https://user-images.githubusercontent.com/72205719/160398726-215ee296-e823-4fd9-8098-df661d94487f.png">
I don't find ops under e2edet

**Comment by kienduynguyen** [comment]
Please build the project following the instruction in README. I corrected the instruction to build BoxeR

**Comment by Zhuyuan-yuan** [comment]
hello
I have compiled boxr, and there is no problem configuring the environment, but when I run pthon test / box_ attn_ test. Py has the following error. How can I solve it?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kienduynguyen/BoxeR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 下午2:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kienduynguyen/BoxeR] ImportError:cannot import name 'ops' from e2edet (Issue #1)





 
Closed #1.

**Comment by kienduynguyen** [comment]
This means the compilation is not done properly. Can you share the output of the compilation? Also, please try to run the tests/box_attn_test.py from your root folder.

**Comment by kienduynguyen** [comment]
I recompiled the Boxer and run from the root folder with "python tests/box_attn_test.py" and it was fine in my machine.

**Comment by Zhuyuan-yuan** [comment]
This is my output of the compilation。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kienduynguyen/BoxeR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 晚上11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kienduynguyen/BoxeR] ImportError:cannot import name 'ops' from e2edet (Issue #1)





 
This means the compilation is not done properly. Can you share the output of the compilation?

**Comment by kienduynguyen** [comment]
Please run command "python  -m pip install -e BoxeR" and share the output with me.

**Comment by Zhuyuan-yuan** [comment]
Since there is no screenshot after the first compliation,th above is the output after the second compilation.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kienduynguyen/BoxeR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月30日(星期三) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kienduynguyen/BoxeR] ImportError:cannot import name 'ops' from e2edet (Issue #1)





 
Please run command "python  -m pip install -e BoxeR" and share the output with me.

**Comment by kienduynguyen** [comment]
Can you open python interpreter and try to import e2edet?
