### ISSUE TITLE
Scripts of running Nuscenes dataset

### ISSUE THREAD

**Issue by Splendon** [kienduynguyen/BoxeR#10]
Hi, thank you very much for this SOTA job.
I have run BoxeR on coco2017 successfully with pytorch1.8.2.
Since waymo dataset is too large, I would like to run BoxeR on nuscenes dataset, is there any some scripts of nuscenes dataset and 2d/3d config.yaml?

**Comment by kienduynguyen** [comment]
Sorry. That's what you need to figure out. The current codebase doesn't support nuscenes but it may come in the future.
