### ISSUE TITLE
How to use the retrained model to evaluate on my own test dataset

### ISSUE THREAD

**Issue by imhumanbean** [kienduynguyen/BoxeR#12]
when i evaluate on my own test dataset, the evaluation looks not work. I just changed the data path on config file.
2022-07-26T10:17:57 INFO: Total Parameters: 39696075. Trained Parameters: 39696075
2022-07-26T10:17:57 INFO: Starting inference on test set
2022-07-26T10:17:57 INFO: Evaluation time. Running on full test set...
2022-07-26T10:19:01 INFO: progress on test: 0/0, 
: --------------------, update: 0, epoch: 0, max_update: 0, num_image: 873
2022-07-26T10:19:02 INFO: The inference finished!

**Comment by kienduynguyen** [comment]
If you wanna see the COCO metrics evaluation, you should set it to val mode. The test mode generates a json file that can be used to submit to the COCO server.

**Comment by imhumanbean** [comment]
> 

thanks a lot. I calculated the metrics I needed from the output JSON file.

**Comment by NiranjanRavi1993** [comment]
Hi @kienduynguyen , 
     I want to visualize the COCO metrics evaluation results. I was able to train the network and generate checkpoint files. From the readMe, I understood I have to use below command:
     python tools/run.py --config e2edet/config/COCO-Detection/boxer2d_R_50_3x.yaml --model boxer2d --task detection training.run_type=val
     Two questions:
     1. How can I set the config file to use my newly generated checkpoint file for evaluation?  Now, I see it utilizes resnet model. 
     2.  @imhumanbean  How did you calculate metrics from the JSON file? I do not see a JSON file generation.
