### ISSUE TITLE
About setup problem

### ISSUE THREAD

**Issue by r10944044** [kienduynguyen/BoxeR#21]
Hi, your work is awesome！
I try to run your recommand command, but I got error message, 
＂　ERROR: Exception: Traceback (most recent call last): File "/data3/reagon/anaconda3/envs/BoxeR/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper status = run_func(*args) File "/data3/reagon/anaconda3/envs/BoxeR/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper return func(self, options, args) File "/data3/reagon/anaconda3/envs/BoxeR/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 377, in run requirement_set = resolver.resolve( File "/data3/reagon/anaconda3/envs/BoxeR/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve result = self._result = resolver.resolve( File "/data3/reagon/anaconda3/envs/BoxeR/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve state = resolution.resolve(requirements, max_rounds=max_rounds) File "/data3/reagon/anaconda3/envs/BoxeR/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve raise ResolutionTooDeep(max_rounds) pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000　＂

my pip version is 23.1.2 and setuptools version is 67.2, and other package version
![1683129651800](https://user-images.githubusercontent.com/91789246/235973019-f93f403d-4cef-45e4-9a38-d3b4dbbbec1e.jpg)
![1683129672605](https://user-images.githubusercontent.com/91789246/235972930-224387e7-4a57-4871-8511-e3a5deff8da2.jpg)

Can you give me some advice？　Thanks！

**Comment by kienduynguyen** [comment]
Hi,

I think it's better to create a new conda env and follow the installation instruction from the README.md to see :D.

**Comment by r10944044** [comment]
I've solved this problem. Remove numba in setup.py, and run your recommand command.

**Comment by kienduynguyen** [comment]
Thanks for your info! If you only care about 2D, removing number should be a good choice since it has conflict with several packages.
