### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by yuanhd17** [kienduynguyen/BoxeR#4]
I have built this project successfully. But when I run the test programs, it reported the lack of memory. It  means that the project cannont run on my laptop?
![Screenshot from 2022-04-06 13-58-15](https://user-images.githubusercontent.com/51024129/161905852-48adf29f-c83d-4a33-9cf7-86395613ab61.png)

**Comment by kienduynguyen** [comment]
Hi. It should be ok. It yields out-of-mem error because I test the box-attention with a high dimension tensor (d=1024). You can run the training script to check further.
