### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Tegala** [kienduynguyen/BoxeR#5]
I appreciate your work, but I found some bugs when using your code. I wonder if you will fix and release a new version in the future?

my env
![image](https://user-images.githubusercontent.com/31198902/164220878-b98426f4-a2fe-4bc9-9f1b-dfed4d758ad6.png)

![image](https://user-images.githubusercontent.com/31198902/164220234-c1b9fd4f-79e9-4a4f-9c11-e9cca500ea76.png)

it seems that u missed return config here in your released version.
![image](https://user-images.githubusercontent.com/31198902/164220146-e075343b-3b1f-4af8-a316-abf5905e9682.png)

**Comment by kienduynguyen** [comment]
Thanks for reporting our bug. I pushed a new commit that should solve your error. The "optimizer.get_stats()" is not supported in current codebase. Please check it another time!
