### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Splendon** [kienduynguyen/BoxeR#9]
Hi,  I have pip installed pytorch1.10.
And when I install e2edet as the readme, this is the following error.
#######
[root@vm-0-3-tlinux /nvmelv/cwh8szh/BoxeR]# python -m pip install -e BoxeR
ERROR: BoxeR is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
#######

And, when I install e2edet with "python setup.py develop" or "pip install -v -e .", it can install e2edet successfully.
#######
Using /root/anaconda3/envs/cwhpy38/lib/python3.8/site-packages
Finished processing dependencies for e2edet==0.1
#######

But, when I run test.py or run.py, it occur the following errors, maybe the pytorch error with e2edet compilation.
#######
Traceback (most recent call last):
  File "tests/box_attn_test.py", line 5, in <module>
    from e2edet.module.ops import BoxAttnFunction
  File "/nvmelv/cwh8szh/BoxeR/e2edet/__init__.py", line 2, in <module>
    import e2edet.model
  File "/nvmelv/cwh8szh/BoxeR/e2edet/model/__init__.py", line 4, in <module>
    from e2edet.model.base_model import BaseDetectionModel
  File "/nvmelv/cwh8szh/BoxeR/e2edet/model/base_model.py", line 14, in <module>
    from e2edet.criterion import build_loss, build_metric
  File "/nvmelv/cwh8szh/BoxeR/e2edet/criterion/__init__.py", line 2, in <module>
    import e2edet.criterion.losses
  File "/nvmelv/cwh8szh/BoxeR/e2edet/criterion/losses.py", line 10, in <module>
    from e2edet.module.matcher import build_matcher
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/__init__.py", line 4, in <module>
    from e2edet.module.transformer import build_transformer
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/transformer.py", line 14, in <module>
    from .box_transformer import BoxTransformer
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/box_transformer.py", line 6, in <module>
    from .box_attention import BoxAttention, InstanceAttention
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/box_attention.py", line 7, in <module>
    from e2edet.module.ops import BoxAttnFunction, InstanceAttnFunction
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/ops/__init__.py", line 1, in <module>
    from e2edet.module.ops.box_attention_func import BoxAttnFunction, InstanceAttnFunction
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/ops/box_attention_func.py", line 6, in <module>
    from e2edet import ops
ImportError: /nvmelv/cwh8szh/BoxeR/e2edet/ops.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIhEEPT_v
#######

#######
(cwhpy38) [root@vm-0-3-tlinux /nvmelv/cwh8szh/BoxeR]# CUDA_VISIBLE_DEVICES=0,1,2,3 python tools/run.py --config e2edet/config/COCO-Detection/boxer2d_R_50_3x.yaml --model boxer2d --task detection training.use_fp16=bfloat16
Traceback (most recent call last):
  File "tools/run.py", line 8, in <module>
    import e2edet
  File "/nvmelv/cwh8szh/BoxeR/e2edet/__init__.py", line 2, in <module>
    import e2edet.model
  File "/nvmelv/cwh8szh/BoxeR/e2edet/model/__init__.py", line 4, in <module>
    from e2edet.model.base_model import BaseDetectionModel
  File "/nvmelv/cwh8szh/BoxeR/e2edet/model/base_model.py", line 14, in <module>
    from e2edet.criterion import build_loss, build_metric
  File "/nvmelv/cwh8szh/BoxeR/e2edet/criterion/__init__.py", line 2, in <module>
    import e2edet.criterion.losses
  File "/nvmelv/cwh8szh/BoxeR/e2edet/criterion/losses.py", line 10, in <module>
    from e2edet.module.matcher import build_matcher
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/__init__.py", line 4, in <module>
    from e2edet.module.transformer import build_transformer
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/transformer.py", line 14, in <module>
    from .box_transformer import BoxTransformer
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/box_transformer.py", line 6, in <module>
    from .box_attention import BoxAttention, InstanceAttention
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/box_attention.py", line 7, in <module>
    from e2edet.module.ops import BoxAttnFunction, InstanceAttnFunction
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/ops/__init__.py", line 1, in <module>
    from e2edet.module.ops.box_attention_func import BoxAttnFunction, InstanceAttnFunction
  File "/nvmelv/cwh8szh/BoxeR/e2edet/module/ops/box_attention_func.py", line 6, in <module>
    from e2edet import ops
ImportError: /nvmelv/cwh8szh/BoxeR/e2edet/ops.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIhEEPT_v
#######

**Comment by Splendon** [comment]
(cwhpy38) [root@vm-0-3-tlinux /nvmelv/cwh8szh/BoxeR]# pip list
Package                     Version      Location
--------------------------- ------------ ---------------------------
absl-py                     0.15.0
addict                      2.4.0
antlr4-python3-runtime      4.8
astunparse                  1.6.3
CacheControl                0.12.10
cachetools                  5.0.0
cachy                       0.3.0
certifi                     2021.10.8
cffi                        1.15.0
charset-normalizer          2.0.12
clang                       5.0
cleo                        0.8.1
clikit                      0.6.2
crashtest                   0.3.1
cryptography                36.0.2
cycler                      0.11.0
Cython                      0.29.27
distlib                     0.3.4
e2edet                      0.1          /nvmelv/cwh8szh/BoxeR
filelock                    3.6.0
flatbuffers                 1.12
fonttools                   4.29.1
gast                        0.4.0
google-auth                 2.6.2
google-auth-oauthlib        0.4.6
google-pasta                0.2.0
grpcio                      1.45.0
h5py                        3.1.0
html5lib                    1.1
idna                        3.3
imageio                     2.16.1
imgaug                      0.4.0
immutabledict               2.2.1
importlib-metadata          4.11.3
jeepney                     0.7.1
keras                       2.9.0
Keras-Preprocessing         1.1.2
keyring                     23.5.0
kiwisolver                  1.3.2
llvmlite                    0.38.0
lockfile                    0.12.2
Markdown                    3.3.6
matplotlib                  3.5.1
mish-cuda                   0.0.3
mmcv-full                   1.4.5
mmdet                       2.22.0       /nvmelv/cwh8szh/mmdetection
msgpack                     1.0.3
networkx                    2.7.1
numba                       0.55.1
numpy                       1.19.5
oauthlib                    3.2.0
omegaconf                   2.2.0
opencv-python               4.5.5.62
opt-einsum                  3.3.0
packaging                   20.9
pandas                      1.4.1
pastel                      0.2.1
pexpect                     4.8.0
Pillow                      8.4.0
pip                         21.2.4
pkginfo                     1.8.2
platformdirs                2.5.1
plotly                      5.8.0
poetry                      1.1.13
poetry-core                 1.0.8
protobuf                    3.19.4
ptyprocess                  0.7.0
pyasn1                      0.4.8
pyasn1-modules              0.2.8
pycocotools                 2.0.4
pycparser                   2.21
pylev                       1.4.0
pyparsing                   3.0.7
python-dateutil             2.8.2
pytorch-wavelets            1.3.0
pytorchyolo                 1.6.2
pytz                        2022.1
PyWavelets                  1.3.0
PyYAML                      6.0
requests                    2.27.1
requests-oauthlib           1.3.1
requests-toolbelt           0.9.1
rsa                         4.8
scikit-image                0.19.2
scipy                       1.8.0
SecretStorage               3.3.1
setuptools                  58.0.4
Shapely                     1.8.1.post1
shellingham                 1.4.0
six                         1.15.0
tenacity                    8.0.1
tensorboard                 2.8.0
tensorboard-data-server     0.6.1
tensorboard-plugin-wit      1.8.1
tensorflow                  2.6.0
tensorflow-estimator        2.9.0
tensorflow-gpu              2.6.0
termcolor                   1.1.0
terminaltables              3.1.10
tifffile                    2022.3.16
tomlkit                     0.10.0
torch                       1.10.1+cu111
torchaudio                  0.10.1
torchsummary                1.5.1
torchvision                 0.11.2+cu111
tqdm                        4.63.1
typing_extensions           4.2.0
urllib3                     1.26.9
virtualenv                  20.13.4
waymo-open-dataset-tf-2-6-0 1.4.7
webencodings                0.5.1
Werkzeug                    2.0.3
wheel                       0.37.1
wrapt                       1.12.1
yapf                        0.32.0
zipp                        3.7.0

**Comment by kienduynguyen** [comment]
Hi,

If you are inside the BoxeR folder, you should run "python -m pip install -e ./". The command "python -m pip install -e BoxeR" is when you are outside of the folder.
